### PR TITLE
Fix requirements - Git is prerequisite to this role

### PR DESCRIPTION
**Pull request by fritz-c**
Add git role to package requirements

### CODE REVIEW

**Comment by fritz-c** [comment]
I'll admit I could be mistaken in my interpretation of the meaning of the `Requirements` section, but it was a bit of a stumbling block when I couldn't proceed without git installed.

**Comment by tschifftner** [comment]
I had the same issue. Please check my [pull request](https://github.com/geerlingguy/ansible-role-dotfiles/pull/2) to have an out of the box working copy.

**Comment by geerlingguy** [comment]
Note that I need to first add macOS support to the `geerlingguy.git` role (basically ensure git is already installed, if not, install via homebrew maybe?) before I can merge this in.

**Comment by geerlingguy** [comment]
I just realized the following was added at some point, recently:

```
Requires git on the managed machine (you can easily install it with geerlingguy.git if required).
```

**Pull request closed without merging**
