### PR TITLE
always_run is deprecated in Ansible 2.4

### PR DESCRIPTION
**Pull request by newtonne**
As per #8, remove `always_run: yes`, and replace with `check_mode: no`. Note that `check_mode` requires Ansible 2.2.

### CODE REVIEW

**Comment by jpartain89** [comment]
Well I'm quite happy I decided to be smart and see if someone else had already taken this on....

**Comment by jpartain89** [comment]
So, what're the chances of this getting taken care of?

**Comment by emielmolenaar** [comment]
https://github.com/geerlingguy/ansible-role-dotfiles/commit/9c2d0cf8f1818786391606fadb5d98eb3ba04016

**Comment by geerlingguy** [comment]
Committed! Sorry about not noticing this earlier.

**Pull request merged**
